### ISSUE TITLE
Cooldown count strata

### ISSUE THREAD

**Issue by Sythral** [StormFX/Masque#19]
I just realized I posted this on wowinterface and the correct method is to go through Github.  Apologize for that!

I am having an issue with the strata of the CD text using blizzards in game cd text on action bars.   https://i.imgur.com/EHxT6rn.png  
The count of the item has a higher strata than the CD text. Without masque, dominos shows the cooldown above the count.

**Comment by StormFX** [comment]
An update to this: The reason this is occurring is because the cool down count is part of the cool down frame. Masque puts the cool down frame below the button frame in order for the "Normal" texture to clip the edges of the cool down animation, to account for odd shapes.

With the ability to customize the cool down texture, it may be that the animation can be masked via an alpha channel and if that's the case, it may not be necessary to lower the frame. I'll look into it.

**Comment by StormFX** [comment]
Another update: I think I may have found a solution for this, but I need to test it in-game a bit more. *fingers crossed*

**Comment by StormFX** [comment]
This should be fixed in the latest alpha. Closing.
