### ISSUE TITLE
Item Button Artifact and Azerite Regions

### ISSUE THREAD

**Issue by Jaliborc** [StormFX/Masque#39]
Please add regions for artifact and azerite item display. Blizzard's container item buttons, for example, call these regions `.IconBorder` and `.IconOverlay`. It seems they intend to use `.IconOverlay` for future item types.

**Comment by StormFX** [comment]
I guess I shouldn't be surprised that they reused the jewel crafting corners, given that's basically all they've done (rehash rehashed content) for the last few expansions. :p I'm assuming that's the `IconBorder`, so what's the overlay do?

**Comment by Jaliborc** [comment]
The bottom image is `IconOverlay`. It shows over the normal artwork and its used to mark azerite items.
The top image is `IconBorder`. It has been in the game since they started highlighting items by rarity. It is the normal quality colored artwork you see on the Supply Bag, and it is replaced by a different fancier texture, still colored by rarity, when an item is an artifact.

Basically they did a mess and implemented the two artworks in completely different manners. Looking at the code, they intend to use `IconOverlay` to apply different artworks to future special item types, instead of using the messier `IconBorder` system.

**Comment by StormFX** [comment]
So the top image, `IconBorder`, is the border that appears only on artifacts while normal items still  use the old border without the corner trim, right? And `IconOverlay` isn't currently used?

**Comment by StormFX** [comment]
So, normal items still use the old border (rarity colors) and overlay (colored, blurred edges like on quest items) and it swaps the textures depending on if it's an artifact or Azerite item? IE, if it's Azerite, the `Overlay' is swapped to the JC-like texture and if it's an artifact, the `Border` is swapped to the other JC-like texture?

**Comment by Jaliborc** [comment]
Almost. If its Azerite the `Overlay` is swapped to the "Azerite Crystal" texture **and shown (its normally a hidden layer)**. You got the artifact one right.

**Comment by StormFX** [comment]
Well, it's normally hidden unless it's a quest item, or in this case, Azerite. :p Anyhow, it sounds like a mess. I'll have to look at it myself. I may add some static settings, but I doubt I'll be bothered with monitoring texture swaps.

I still have to figure out how the hell Blizzard animates the edge texture for cool downs so I can see if I can mask it or something. It's annoying that they implemented alpha-masks for the swipe texture but not the edge texture. I'd like to be able to put the cool down frame back where it belongs instead of clipping it by placing it below the `Normal` texture.

**Comment by StormFX** [comment]
Sorry for the delay on this. A couple of things:

- Bagnon doesn't use the IconBorder region, it uses the Border region. I'm not sure if this is due to Masque not supporting the IconBorder or if it's just being reused.
- Only the size and offsets will be supported at the moment. The colors and textures are controlled by the game/add-on.

**Comment by Jaliborc** [comment]
- Yes, Bagnon just lets the default UI code "do its own thing" to the `IconOverlay` and `IconBorder` textures.
- Alright

**Comment by StormFX** [comment]
As I mentioned and if memory serves from my tests, Bagnon uses the `Border` region, _not_ the `IconBorder` region. The default UI uses the `IconBorder` region.

**Comment by StormFX** [comment]
Ignore my previous comment. Bagnon actually uses a custom region. In any case, the latest alpha should address this, so closing.
