### ISSUE TITLE
border bugs 

### ISSUE THREAD

**Issue by Nukme** [StormFX/Masque#67]
Version: 
8.2.5-beta

Settings: 
Classic theme + Dominos + Clean Icons: Thin

Descriptions: 
1. black pixels around the corner of buttons on action bars, which makes buttons looking aliased.
2. GCD cooldown animation would cover the GLOW effect, which just ruins the action bar in combat.

Something else:
The old "Blizzard" masque theme + dominos is just perfect for me. In fact, I haven't changed my action bar style since 2011. With this re-worked beta version, I have to retune Masque and Dominos and end up very SAD. Everything seems off and weird.  The borders in Classic theme aren't as bright as Blizzard theme and with the increased size of Classic theme, I have to shrink action bar buttons via Dominos, which makes the borders thin and stack texts on buttons small.

Is it too much to ask for a built-in "Blizzard" legacy theme? Or a "Masque: Blizzard" standalone plug-in?

**Comment by StormFX** [comment]
> black pixels around the corner of buttons on action bars, which makes buttons looking aliased.

Clean Icons and _Masque_ aren't suited to work together, especially with the default set of skins.

> GCD cooldown animation would cover the GLOW effect, which just ruins the action bar in combat.

_Masque_ no longer changes the frame strata of any frames, so this isn't an issue with _Masque_.

> With this re-worked beta version, I have to retune Masque and Dominos and end up very SAD. Everything seems off and weird.

The primary change was adjusting the size to the standard 36 x 36 pixels. The original was too small when at a UI scale of 1.0, which is the baseline for skins.

> The borders in Classic theme aren't as bright as Blizzard theme

This doesn't make any sense. They're the same texture. There are no color/alpha changes.

> Is it too much to ask for a built-in "Blizzard" legacy theme? Or a "Masque: Blizzard" standalone plug-in?

The skin was renamed to "Classic" because "Blizzard" for legal reasons. That said, I may consider incorporating a version of "Classic" that more closely resembles the previous version. We'll see.

**Comment by Nukme** [comment]
Thanks for the reply!

> Masque no longer changes the frame strata of any frames, so this isn't an issue with Masque.

One of my WAs is causing the glow frame strata issue, tho I don't quite understand why. Solved by detaching the WA from action bar frames.

>Clean Icons and Masque aren't suited to work together, especially with the default set of skins.

I take screenshots of my action bar buttons (200% via Dominos) under Masque 8.0.1 and 8.2.5 respectively, both with Clean Icons. 

8.0.1 "Blizzard":
<img src="https://i.ibb.co/1ZcQrTp/8-0-1.png" alt="8-0-1" border="0">

8.2.5 "Classic":
<img src="https://i.ibb.co/kHqDBrv/8-2-5.png" alt="8-2-5" border="0">

The difference is obvious. 8.0.1 renders clean cut corners, while the 8.2.5 seems to have un-masked black backdrop.

Would you take a look into this? Thx!

**Comment by StormFX** [comment]
> The difference is obvious. 8.0.1 renders clean cut corners, while the 8.2.5 seems to have un-masked black backdrop.

As I mentioned, Clean Icons and Masque don't really work together. What you're seeing there is Clean Icon's borders because they've made the icons square. The default icons are transparent and have slightly rounded corners. The difference between 8.0.1 and 8.2.5b is that the icon sizes have been increased by a few pixels to hide the inside of the metal border of the artwork. That said, I'm going to try to trim the icons with texture coordinates to see if I can shrink them a little to hide the corners. That should fix the issue universally.

**Comment by Nukme** [comment]
Great! Thanks for your work!

**Comment by StormFX** [comment]
Is it close enough to the original?

**Comment by Nukme** [comment]
Sure. The trim does the magic, and I can work with the button size. THX!

**Comment by StormFX** [comment]
Good deal. Closing.
